server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/messagedb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      initialization-fail-timeout: 60000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  activemq:
    broker-url: tcp://activemq:61616
    user: admin
    password: admin
  jms:
    listener:
      acknowledge-mode: AUTO
      concurrency: 1
    pub-sub-domain: false

logging:
  level:
    com.example.backend: DEBUG
    org.springframework.transaction: DEBUG
    org.springframework.jms: DEBUG
    org.springframework.orm.jpa: DEBUG 