server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/messagedb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      initialization-fail-timeout: 60000

  activemq:
    broker-url: tcp://activemq:61616
    user: admin
    password: admin
  jms:
    listener:
      session:
        acknowledge-mode: AUTO
      min-concurrency: 1
    pub-sub-domain: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

logging:
  level:
    com.example.backend: DEBUG
    org.springframework.transaction: DEBUG
    org.springframework.jms: DEBUG 