server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/messagedb?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  activemq:
    broker-url: tcp://activemq:61616
    user: admin
    password: admin

logging:
  level:
    com.example.backend: DEBUG 