version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: messagedb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  activemq:
    image: rmohr/activemq:5.15.9
    ports:
      - "61616:61616"
      - "8161:8161"
    environment:
      - ACTIVEMQ_ADMIN_LOGIN=admin
      - ACTIVEMQ_ADMIN_PASSWORD=admin

  frontend:
    build: ./message-frontend
    ports:
      - "8080:8080"
    environment:
      - SPRING_ACTIVEMQ_BROKER_URL=tcp://activemq:61616
      - SPRING_ACTIVEMQ_USER=admin
      - SPRING_ACTIVEMQ_PASSWORD=admin
    depends_on:
      - activemq

  backend:
    build: 
      context: ./message-backend
    ports:
      - "8082:8082"
    depends_on:
      - mysql
      - activemq
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/messagedb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_ACTIVEMQ_BROKER_URL: tcp://activemq:61616

volumes:
  mysql_data: 